[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sdmlx"
version = "0.1.17"
description = "ComfyUI node suite for faster SDXL image generation on Apple Silicon with MLX."
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "mlx>=0.10.0",
    "safetensors",
    "huggingface_hub",
    "numpy",
    "transformers",
    "regex",
    "psutil",
    "tqdm",
    "insightface",
    "onnxruntime",
    "gguf",
]
classifiers = [
    "Operating System :: MacOS",
]

[project.urls]
Repository = "https://github.com/elef4nt-gh/SDMLX"
Documentation = "https://github.com/elef4nt-gh/SDMLX#readme"
"Bug Tracker" = "https://github.com/elef4nt-gh/SDMLX/issues"

[tool.comfy]
PublisherId = "elef4nt"
DisplayName = "SDMLX"
Icon = "https://raw.githubusercontent.com/elef4nt-gh/SDMLX/main/resources/sdmlx.png"
